Initial integration for Azure Devops to JupiterOne
JupiterOne/graph-azure-devops pull request #1
Opened 2021-01-08 19:19 UTC by kevincasey1222

This integration uses azure-devops-node-api (https://github.com/microsoft/azure-devops-node-api) and the Jupiter One integration template. It stays pretty close to the template, with additional inspiration drawn from https://github.com/JupiterOne/graph-qualys

It currently gathers 5 types of objects - Account, Projects, Users, UserGroups (teams in ADO), and Workitems. Though workitems in ADO can have complex relationships, in this integration they are all owned by the Project. The details of the complex relationships are made available through properties in the Record object in J1, if someone wants to use J1QL for a deep dive.

Tests use a recording and compare it to a snapshot, both drawn from a test account I made in ADO with just a few projects, users, teams, and workitems.

2021-01-09 03:39 UTC, aiwilliams requested changes
Thanks for your work on this integration!

I'm really interested in hearing whether there is an offsite/OAuth flow for obtaining an access token, instead of using a personal access token. If that path is supported, it could be accomplished in a different PR, but we'll need to document that a personal access token is the only choice if that is the case. In either case, we'll need the `docs/development.md` doc to indicate how to go about getting the authentication access token.

2021-01-09 03:39 UTC, aiwilliams commented on src/steps/users/index.ts
> +            _key: user.identity?.id,
`_key` cannot be `undefined`. It would be good to avoid creating this entity when `user.identity` is `undefined`, perhaps using a guard clause before constructing/adding the entity.

```ts
if (!user.identity?.id) {
  logger.info('Skipping user resource where user.identity is undefined');
  return;
}
```

2021-01-09 03:39 UTC, aiwilliams commented on src/steps/users/index.ts
> +//import { ResultGroupType } from 'azure-devops-node-api/interfaces/TestInterfaces';
Are these commented lines (and others like them) intended to be used in an upcoming PR? Let's delete them if not, otherwise they look like construction debris.

2021-01-09 03:39 UTC, aiwilliams commented on src/steps/users/index.ts
> +            webLink: user.identity?.url,
Is this `identity.url` something that would serve better than the `identity.profileUrl`? The `webLink` property is meant to take someone to the best representation of the resource in the source system.

2021-01-09 03:39 UTC, aiwilliams commented on src/types.ts
> +  // clientSecret: string; // not used
These can be deleted.

2021-01-09 03:39 UTC, aiwilliams commented on src/types.ts
> +   * The personal access token used to authenticate requests.
Is there an authentication scheme that would allow us to avoid a personal access token? These personal tokens are attached to a specific user, which limits them to the permissions of that user, and are in most systems invalidated when that user is removed so that a background process like these integrations would stop working.

2021-01-09 03:39 UTC, aiwilliams commented on src/validateInvocation.test.ts
> +  //IntegrationProviderAuthenticationError,
Ideally there'd be a test with recording that demonstrates this function attempts to use the credentials to verify they authenticate before any steps are run.

2021-01-09 03:39 UTC, aiwilliams commented on src/steps/index.test.ts
> +  //expect(projects.length).toBeGreaterThan(0);
Is this check unnecessary? IIRC, the `toMatchGraphObjectSchema` is going to be happy even when there are 0 entries in the array, which means these tests could pass even when no data is collected, or when the `filter` function above doesn't work as expected.

2021-01-09 03:39 UTC, aiwilliams commented on src/instanceConfigFields.ts
> +  },*/
```suggestion
```

2021-01-09 03:39 UTC, aiwilliams commented on src/client.ts
> +        endpoint: 'ADO API', //'https://localhost/api/v1/some/endpoint?limit=1',
When we don't know the URL, because it's maintained by the client library, the `endpoint` can be the resource being fetched. This helps in error handling/logging to know what was being requested. For example:
```
        endpoint: 'getAllTeams',
```

2021-01-09 03:39 UTC, aiwilliams commented on src/client.ts
> +          );
It would be ideal to have this API call in a different `try/catch` block so that the thrown `IntegrationProviderAuthenticationError` can have an appropriate `endpoint`, such as `getTeamMembersWithExtendedProperties`.

2021-01-09 03:39 UTC, aiwilliams commented on src/client.ts
> +            if (teamMember.identity?.id != undefined) {
```suggestion
            if (teamMember.identity?.id) {
```
This is sufficient, unless `id` could be `0`. If the comparison is required, `!==` does an identity check (instead of equality) which is best for `undefined` comparisons.

2021-01-09 03:39 UTC, aiwilliams commented on src/client.ts
> +                .includes(teamMember.identity?.id)
I wonder if there could be a problem here should the code resolve to:
```ts
[undefined, undefined, undefined].includes(undefined)
```

2021-01-09 03:39 UTC, aiwilliams commented on src/client.ts
> +        if (team.projectId != undefined && team.id != undefined) {
```suggestion
        if (team.projectId && team.id) {
```

2021-01-09 16:07 UTC, kevincasey1222 commented on yarnout
> +$ j1-integration collect
Construction debris

2021-01-09 16:08 UTC, kevincasey1222 commented on src/validateInvocation.test.ts
>    }
Got it. I made the changes that were made in JupiterOne/integration-template#21

2021-01-09 16:09 UTC, kevincasey1222 commented on src/steps/workitems/index.ts
> +            type: (item.fields || {})['System.WorkItemType'],
Done. Thanks. I should have thought of that. Much cleaner.

2021-01-09 16:09 UTC, kevincasey1222 commented on src/steps/users/index.ts
> +            _key: user.identity?.id,
Added.

2021-01-09 16:09 UTC, kevincasey1222 commented on src/steps/users/index.ts
> +//import { ResultGroupType } from 'azure-devops-node-api/interfaces/TestInterfaces';
Cleaned this up, and several similar lines in other files.

2021-01-09 16:24 UTC, kevincasey1222 commented on src/steps/users/index.ts
> +            webLink: user.identity?.url,
On my test account, `identity.profileUrl` came back as undefined for my project team members, whereas `identity.url` was always defined. I suspect that `identity.profileUrl` is referring to software certificate profiles (ie. permissions) rather than a user's profile in a social media sense.

2021-01-09 16:30 UTC, kevincasey1222 commented on src/steps/index.test.ts
> +  //expect(projects.length).toBeGreaterThan(0);
Erich and I debated this point, which is why I left the comment in there for discussion. Arguably, a person could setup an ADO account with no projects, just to test the basic function of the integration... but it's a useless account, so I could see us throwing an error in such a case. I'll un-comment that line.

2021-01-09 16:37 UTC, kevincasey1222 commented on src/client.ts
> +        endpoint: 'ADO API', //'https://localhost/api/v1/some/endpoint?limit=1',
Excellent. I made updates to all these cases in that file.

2021-01-09 16:38 UTC, kevincasey1222 commented on src/client.ts
> +            if (teamMember.identity?.id != undefined) {
I don't know if there is a chance of `teamMember` having an `id` of 0. It seems unlikely, but just in case, I went with `!==` here. On most of the other cases (like project id and team id) I just simplified the if condition per your indication here.

2021-01-09 16:39 UTC, kevincasey1222 commented on src/client.ts
> +                .includes(teamMember.identity?.id)
Changed to `teamMember.identity?.id &&
              !users
                .map((x) => x.identity?.id)
                .includes(teamMember.identity?.id)`

2021-01-09 16:40 UTC, kevincasey1222 commented on src/client.ts
> +                .includes(teamMember.identity?.id)
So a `teamMember` with `.identity.id` undefined will never be added to the array.

2021-01-09 16:40 UTC, kevincasey1222 commented on src/client.ts
> +        if (team.projectId != undefined && team.id != undefined) {
Done.

2021-01-09 16:41 UTC, kevincasey1222 commented on src/instanceConfigFields.ts
> +  },*/
Done.

2021-01-09 16:42 UTC, kevincasey1222 commented on src/types.ts
> +  // clientSecret: string; // not used
Done.

2021-01-09 16:43 UTC, kevincasey1222 commented on src/steps/index.test.ts
> +  //expect(projects.length).toBeGreaterThan(0);
Uncommented in the last commit.

2021-01-09 16:49 UTC, kevincasey1222 commented
Overall, I really appreciate you taking the time to go through every line of my first project for J1. I see that many of the items were due to lack of experience. I appreciate you pointing them out, and promise that you only have to tell me that simple stuff one time.

On the topic of moving from a personal access token to OAuth, I wondered about that conceptually, but I didn't have experience with OAuth, and I set it aside that thought aside in the interest of getting a working integration finished. A cursory Goggle search makes it seem that there is an OAuth path. I'll read up on it to get a sense for how complicated it is.

2021-01-11 14:59 UTC, aiwilliams commented
> On the topic of moving from a personal access token to OAuth, I wondered about that conceptually, but I didn't have experience with OAuth, and I set it aside in the interest of getting a working integration finished.

Thanks @kevincasey1222, I think that was the right thing to do (focus on getting access and ingesting data). 👍 

> A cursory Goggle search makes it seem that there is an OAuth path. I'll read up on it to get a sense for how complicated it is.

Okay, great. Please add your findings to https://github.com/JupiterOne/graph-azure-devops/issues/2. I wouldn't spend too much time on it even now beyond identifying the documentation/process. I wonder if it's the same thing that we'll be needing to do for the Microsoft 365 integration ([a work in progress](https://github.com/JupiterOne/graph-microsoft-365/blob/initial-release/docs/development.md#authentication)), which leverages the [Microsoft Identity Platform](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#protocol-diagram).

In any case, the implementation will require close collaboration with the J1 team because we have to coordinate things in the application. That is, this is not something that can be implemented by a contractor alone.

2021-01-11 15:00 UTC, aiwilliams commented on src/client.ts
> +          );
I think it'd be good to pull this into it's own `try/catch` now so that we can have a distinct `IntegrationProviderAuthenticationError.endpoint` value, otherwise, if this line throws, we'll be told the error was for `ADO WebApi.getCoreApi.getAllTeams`.

2021-01-11 15:01 UTC, aiwilliams commented on src/client.ts
> +          );
Oops, wrong place for this comment. Will comment in correct place.

2021-01-11 15:02 UTC, aiwilliams commented on src/client.ts
> +          );
This is the place I meant to say, "we can have a distinct `IntegrationProviderAuthenticationError.endpoint` value, otherwise, if this line throws, we'll be told the error was for `ADO WebApi.getCoreApi.getAllTeams`".

2021-01-11 22:16 UTC, kevincasey1222 commented on src/client.ts
> +          );
Alright, that's been done in the refactor of client.ts I just pushed, and similar changes implemented for all the API calls in that file.

2021-01-12 15:41 UTC, mknoedel reviewed
This looks great, thank you for your great work!

2021-01-13 17:37 UTC, merged