repetitive code removed
JupiterOne/graph-azure-devops pull request #26
Opened 2024-03-15 09:22 UTC by Bharatkk-metron

2024-03-22 07:51 UTC, suraj-metron commented
We have not updated CHANGELOG.md file @Bharatkk-metron

2024-03-22 10:58 UTC, suraj-metron requested changes

2024-03-22 10:58 UTC, suraj-metron commented on src/client.ts
I dont see nay default timeout for API calls. Does Azure SDK provides the same?

2024-03-22 10:58 UTC, suraj-metron commented on src/steps/alerts/index.ts
> +        category: alert.alertType ? AlertType[alert.alertType] : undefined,
Instead of undefined, lets assign the Unknown value in ALert Type. Same should be done for below ones

2024-03-22 11:06 UTC, Bharatkk-metron commented on docs/jupiterone.md
> +| ADO Project            | `azure_devops_project`        | `Project`       |
that's correct

2024-03-22 11:09 UTC, Bharatkk-metron commented on src/client.test.ts
> +        `Provider authentication failed at ${configWithInvalidAccessToken.orgUrl}/_apis/core: 401 Failed request: (401)`,
yes. I made this more granular.

2024-03-22 11:12 UTC, Bharatkk-metron commented on src/steps/alerts/index.test.ts
> +    unit_test_custom_timeout,
The timeout spelling is corrected.

2024-03-22 11:14 UTC, Bharatkk-metron commented on src/steps/repos/index.ts
> +          `Build-Account-Repo-Relationship: ${accountKey} Missing.`,
this is just string. There is no standard for this.

2024-03-22 11:15 UTC, Bharatkk-metron commented on src/client.ts
is retry function I have added that retries if the error is retryable.

2024-03-22 11:21 UTC, Bharatkk-metron commented on src/steps/repos/index.test.ts
> +    // expect(mappedRelationships.length).toBeGreaterThan(0);
We don't have data for GitHub and Bitbucket repos to test the mapped relationships. However since it was already developed in the previous iteration, we assume the code is valid. This can be used if data is there in the future.

2024-03-22 11:22 UTC, Bharatkk-metron commented on jupiterone/questions/questions.yaml
> +      - environment
added.

2024-03-22 11:26 UTC, Bharatkk-metron commented on src/steps/constant.ts
> +    _class: ['Repository'],
As it was, they changed the Class name for the entity but not in the unit test file. The unit test was failing due to this.
If we check in the constant file there is no entity with class name coderepo.

2024-03-22 11:26 UTC, Bharatkk-metron commented on src/steps/devopsService/index.ts
> +    relationships: [], // TODO: Create Relationship
removed.

2024-03-22 11:27 UTC, Bharatkk-metron commented on src/steps/repos/index.ts
> +    name: 'Build Accont Repo Relationship',
corrected

2024-03-22 11:28 UTC, Bharatkk-metron commented on src/client.ts
there is not standard document for this and in previous version also the data was being fetched all in once.

2024-03-22 11:30 UTC, Bharatkk-metron commented on src/steps/alerts/index.ts
> +        category: alert.alertType ? AlertType[alert.alertType] : undefined,
Done.

2024-04-01 17:28 UTC, suraj-metron commented on src/client.test.ts
> +        'Provider authentication failed at https://dev.azure.com/a-very-invalid-org-url/_apis/core: undefined Failed to find api location for area: Location id: e81700f7-3be2-46de-8624-2eb35882fcaa',
@Bharatkk-metron This is unattended

2024-04-01 17:29 UTC, suraj-metron commented on src/steps/constant.ts
> +    _class: ['Repository'],
Okay

2024-04-01 17:34 UTC, suraj-metron commented on src/steps/repos/index.ts
> +          `Build-Account-Repo-Relationship: ${accountKey} Missing.`,
Okay, since we are trying to log the error for a particular. I would suggest keeping it same as the step name

2024-04-01 17:34 UTC, suraj-metron commented on src/steps/constant.ts
> +  BUILD_ACCONT_REPO_RELATIONSHIP: 'build-account-repo-relationship',
Typo: BUILD_ACCONT

2024-04-01 17:34 UTC, suraj-metron commented on src/client.ts
ok

2024-04-01 17:34 UTC, suraj-metron commented on src/client.ts
ok

2024-04-01 17:35 UTC, suraj-metron commented on src/client.ts
Did we checked this?

2024-04-02 03:45 UTC, Bharatkk-metron commented on src/client.ts
yes, we added the same Please check this function:  fetchDataFromAzureDevOpsWithRetry.

2024-04-04 17:51 UTC, suraj-metron commented on src/client.ts
ok

2024-04-04 17:52 UTC, suraj-metron approved these changes

2024-04-04 17:53 UTC, merged